import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main_container}>
        <h1 className="main-title">Ciberespacio artístico de Kennedy</h1>
        <section id='multiple-logos-section'>

        </section>        
      </div>
    </>
  )
}
