import Head from 'next/head';
import Image from 'next/image';
import Map from "react-map-gl";
import "mapbox-gl/dist/mapbox-gl.css";
import styles from '@/styles/Home.module.css';

export default function Home() {
  const mapboxToken = "pk.eyJ1IjoianVhbmZlbDI1NCIsImEiOiJjbGlkYnpsdHYwMWUxM21tbzJydGt4NXZ1In0.WkzTOoZyMsPBNymYAJzCdw"

  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main_container}>
        <h1 className="main-title">Ciberespacio artístico de Kennedy</h1>
        
        <Map
          mapboxAccessToken={mapboxToken}
          mapStyle="mapbox://styles/mapbox/streets-v12"
          style={{ width: "100%", height: "500px" }}
          initialViewState={{ latitude: 4.6299331, longitude: -74.1725814, zoom: 12 }}
          maxZoom={20}
          minZoom={3}
        ></Map>

        <section className={styles.multiple_logos_section}>
          
          <div className={styles.created_by}>
            <h2>Creado Por</h2>
            <Image
              src="/main-logos/logotipo-cibermedia-blanco.svg"
              width={200}
              height={120}
              alt="Logo del Colectivo Cultural Cibermedia"
              className="home-logo cibermedia-home-logo"
            />
          </div>

          <div className={styles.supported_by_container}>
            <h2>Con el apoyo de</h2>
            <ul className={styles.supported_by_logos}>
              <li>
                <Image
                  src="/main-logos/logotipo-la-bogota-que-estamos-construyendo.svg"
                  width={200}
                  height={120}
                  alt="Logo de la Bogotá que estamos construyendo"
                  className="home-logo"
                />  
              </li>
              <li>
                <Image
                  src="/main-logos/logo-kennedy-es-cultura-local.svg"
                  width={200}
                  height={120}
                  alt="Logo de Kennedy es cultura local"
                  className="home-logo"
                />  
              </li>
              <li>
                <Image
                  src="/main-logos/logotipo-les-lumiere-blanco.svg"
                  width={200}
                  height={120}
                  alt="Logo de la Corporación Cultural Les Lumiere"
                  className="home-logo"
                />  
              </li>
              <li>
                <Image
                  src="/main-logos/logotipo-nakuma-blanco.svg"
                  width={200}
                  height={120}
                  alt="Logo de Nakuma Cultura Creativa"
                  className="home-logo"
                />  
              </li>
            </ul>

          </div>
        </section>

      </div>
    </>
  )
}
