import Head from 'next/head';
import Image from 'next/image';
import KennedyMap from '@/components/kennedyMap/kennedyMap';
import styles from '@/styles/Home.module.css';

export default function Home() {

  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main-container">
        <h1 className="main-title">Ciberespacio artístico de Kennedy</h1>

        <KennedyMap />

        <section className={styles.multiple_logos_section}>
          
          <div className={styles.created_by}>
            <h2>Creado Por</h2>
            <Image
              src="/main-logos/logotipo-cibermedia-blanco.svg"
              width={200}
              height={120}
              alt="Logo del Colectivo Cultural Cibermedia"
              className="home-logo cibermedia-home-logo"
            />
          </div>

          <div className={styles.supported_by_container}>
            <h2>Con el apoyo de</h2>
            <ul className={styles.supported_by_logos}>
              <li>
                <Image
                  src="/main-logos/logotipo-la-bogota-que-estamos-construyendo.svg"
                  width={200}
                  height={120}
                  alt="Logo de la Bogotá que estamos construyendo"
                  className="home-logo"
                />  
              </li>
              <li>
                <Image
                  src="/main-logos/logo-kennedy-es-cultura-local.svg"
                  width={200}
                  height={120}
                  alt="Logo de Kennedy es cultura local"
                  className="home-logo"
                />  
              </li>
              <li>
                <Image
                  src="/main-logos/logotipo-les-lumiere-blanco.svg"
                  width={200}
                  height={120}
                  alt="Logo de la Corporación Cultural Les Lumiere"
                  className="home-logo"
                />  
              </li>
              <li>
                <Image
                  src="/main-logos/logotipo-nakuma-blanco.svg"
                  width={200}
                  height={120}
                  alt="Logo de Nakuma Cultura Creativa"
                  className="home-logo"
                />  
              </li>
            </ul>

          </div>
        </section>

      </div>
    </>
  )
}
